#ifndef AESNIENCOFB_H
#define AESNIENCOFB_H

#include <wmmintrin.h>

namespace {

/* OFB (Output Feedback) mode.
 *
 * The keystream is generated by repeatedly encrypting the previous output block
 * with the forward AES cipher. Encrypt and decrypt are identical.
 *
 * O[0] = AES_E(IV)
 * O[i] = AES_E(O[i-1])
 * out[i] = in[i] XOR O[i]
 *
 * Partial last block (length % 16 != 0) is handled byte-by-byte so the
 * output length always equals the input length. */

void AES_OFB_xcrypt(const unsigned char *in,
                    unsigned char *out,
                    unsigned char ivec[16],
                    unsigned long length,
                    const char *key,
                    int number_of_rounds)
{
    __m128i feedback, tmp, data;
    unsigned long i;
    int j;

    const unsigned long blocks    = length / 16;
    const unsigned long remainder = length % 16;

    feedback = _mm_loadu_si128((__m128i*)ivec);

    for (i = 0; i < blocks; i++) {
        /* Generate next output block: O[i] = AES_E(O[i-1]). */
        tmp = _mm_xor_si128(feedback, ((__m128i*)key)[0]);
        for (j = 1; j < number_of_rounds; j++)
            tmp = _mm_aesenc_si128(tmp, ((__m128i*)key)[j]);
        feedback = _mm_aesenclast_si128(tmp, ((__m128i*)key)[j]);

        data = _mm_loadu_si128((const __m128i*)(in + i * 16));
        _mm_storeu_si128((__m128i*)(out + i * 16), _mm_xor_si128(feedback, data));
    }

    /* Partial last block: generate one more output block, XOR byte-by-byte. */
    if (remainder > 0) {
        unsigned char keystream[16];
        tmp = _mm_xor_si128(feedback, ((__m128i*)key)[0]);
        for (j = 1; j < number_of_rounds; j++)
            tmp = _mm_aesenc_si128(tmp, ((__m128i*)key)[j]);
        tmp = _mm_aesenclast_si128(tmp, ((__m128i*)key)[j]);
        _mm_storeu_si128((__m128i*)keystream, tmp);

        for (unsigned long k = 0; k < remainder; k++)
            out[blocks * 16 + k] = in[blocks * 16 + k] ^ keystream[k];
    }
}

} // namespace

#endif // AESNIENCOFB_H
